// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8q52_lgO2qiupBlw7BKVYcTYx-JwbBIw',
    appId: '1:530804551525:web:d0f323f7988528309abb8c',
    messagingSenderId: '530804551525',
    projectId: 'ridedekho-cus',
    authDomain: 'ridedekho-cus.firebaseapp.com',
    storageBucket: 'ridedekho-cus.appspot.com',
    measurementId: 'G-1EKP8CD5P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj87DTlevXsBexsRmfmVFzGnzZKr2ArHw',
    appId: '1:530804551525:android:3e1bd6ad13abd8cf9abb8c',
    messagingSenderId: '530804551525',
    projectId: 'ridedekho-cus',
    storageBucket: 'ridedekho-cus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1lk4a4nytszT9ihkPFyn-JexuYTrxAeQ',
    appId: '1:530804551525:ios:d25fc165e72d72b79abb8c',
    messagingSenderId: '530804551525',
    projectId: 'ridedekho-cus',
    storageBucket: 'ridedekho-cus.appspot.com',
    iosBundleId: 'com.ridedekho.customer',
  );
}
